# InventoryFull+
# Author: ItsLewizzz
# Copyright (c) Lewis D 2016-2022. All Rights Reserved.

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# MESSAGES
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

messages:
  prefix: '{#5cd7b0}InventoryFull+ {#a5b1c2}›'
  reload: '{PREFIX} &fThe configuration has been reloaded in {TIME}ms.'
  no_permission: '{PREFIX} &fYou do not have permission to execute this command.'

  toggle_enable: '{PREFIX} &fYou have toggled notifications: {#4cd137}&lON'
  toggle_disable: '{PREFIX} &fYou have toggled notifications: {#e84118}&lOFF'

  help:
    - "&r"
    - " {#5cd7b0}&lInventoryFull+ {#a5b1c2}v{VERSION}"
    - "  {#a5b1c2}By ItsLewizzz"
    - "&r"
    - " {#5cd7b0}&lCommands"
    - "  &f/inventoryfull reload {#a5b1c2}- &fReload the configuration"
    - "  &f/inventoryfull toggle {#a5b1c2}- &fToggle alert notifications."
    - "&r"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# GENERAL SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Cooldown time to send inventory full alerts (in seconds)
# Set to 0 to disable
cooldown_time: 3

# Prevent block breaking when their inventory is full
prevent_block_breaking: false

# Gamemodes that will not receive inventory full notifications
disabled_gamemodes:
  - CREATIVE
  - SPECTATOR

# Worlds that will not receive inventory full notifications
disabled_worlds:
  - world_the_end
  - disabled_world_here

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# ALERT SETTINGS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Actions List
#
# [ACTIONBAR] <message>
# [BROADCAST] <message>
# [COMMAND] <command>
# [CONSOLE] <command>
# [MESSAGE] <message>
# [SOUND] <sound value>
# [TITLE] <title;subtitle;fadeIn;stay;fadeOut>
#
actions:
  - "[ACTIONBAR] {#5cd7b0}InventoryFull+ {#a5b1c2}› &fYour inventory is full!"
  - "[TITLE] {#5cd7b0}&lALERT;&fYour inventory is full!;1;2;1"
  - "[SOUND] BLOCK_NOTE_BLOCK_PLING"
  - "[MESSAGE] {#a5b1c2}&m-------------------"
  - "[MESSAGE]          {#5cd7b0}&lALERT"
  - "[MESSAGE] &fYour inventory is full!"
  - "[MESSAGE] {#a5b1c2}&m-------------------"

# Requires HolographicDisplays or CMI
hologram:
  enabled: true
  display_time: 3 # in seconds
  lines:
    - '{#5cd7b0}&lALERT'
    - '&fYour inventory is full!'