name: InventoryFullPlus
version: @version@
authors: [ItsLewizzz]
description: Notify players when their inventory is full

main: fun.lewisdev.inventoryfull.InventoryFullPlusPlugin
api-version: 1.13

softdepend:
  - HolographicDisplays
  - CMI
  - DecentHolograms
  - AutoSell

permissions:
  inventoryfull.admin:
    default: op
  inventoryfull.toggle:
    default: op
